version: '2'


services:

  spring-boot-example:
    image: ci.docapost.io/spring-boot-example:latest
    entrypoint:
      - java
      - -cp
      - /USR/newtprod/spring-boot-example/jars/*:/USR/newtprod/spring-boot-example/conf
      - org.springframework.boot.loader.JarLauncher
    ports:
      - "10104:10104"
